name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push ckan
        uses: docker/build-push-action@v3
        with:
          context: ../../
          push: true
          tags: radicalgeektechnology/ckan:latest
      -
        name: Build and push db
        uses: docker/build-push-action@v3
        with:
          context: ../../
          file: contrib/docker/postgresql/Dockerfile
          push: true
          tags: radicalgeektechnology/postgres:latest
      -
        name: Build and push solr
        uses: docker/build-push-action@v3
        with:
          context: ../../
          file: contrib/docker/solr/Dockerfile
          push: true
          tags: radicalgeektechnology/solr:latest
